import Header from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Provider } from "react-wrap-balancer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Schnitzer | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
