import Providers from "@/Redux/Providers";
import Header from "./components/Header";
import NextAuthProvider from "./components/NextAuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Schnitzer | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NextAuthProvider>
            <Header />
            {children}
          </NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
